- README.md
- database.sql
- package-lock.json
- package.json
- src/app.js
- src/database/bearerTokenDBHelper.js
- src/database/msSqlWrapper.js
- src/database/userDBHelper.js
- src/index.js
- src/routes/root.js
- src/routes/users.js
Fix the start script using babel-register instead of ngx. Add some minor changes.
> Switch to vini-database as DB. 

- database.sql
- src/database/accessTokensDBHelper.js
saveAccessToken (björn em, sebastian j)
> Database Query

- .gitignore
- package-lock.json
- test/accounts/administration.test.js
- test/accounts/carAccount.test.js
- test/accounts/userAccount.test.js
- test/authorisation/accessTokenModel.test.js
- test/authorisation/authRoutesMethods.test.js
- test/blockchain/ethNode.test.js
- test/blockchain/transaction.test.js
- test/blockchain/transactionPayload.test.js
- test/database/accessTokensDBHelper.test.js
- test/database/msSqlWrapper.test.js
- test/database/userDBHelper.test.js
- test/routes/api/car/applyCancelTransaction.test.js
- test/routes/api/car/cancelTransaction.test.js
- test/routes/api/car/mileage.test.js
- test/routes/api/car/register.test.js
- test/routes/api/car/root.test.js
- test/routes/api/car/service.test.js
- test/routes/api/car/tuev.test.js
- test/routes/api/login.test.js
- test/routes/api/user_register.test.js
- test/routes/root.test.js
> - Add testfiles

- src/blockchain/ethNode.js
- src/blockchain/transaction.js
- src/blockchain/transactionPayload.js
let subscription = web.eth.subscribe(); //might be useful for error handling and such
> added Trsanction and TransactionPayload stub/scaffolding

- README.md
- RestAPI.postman_collection.json
- package-lock.json
- src/routes/ReadMe.md
- src/routes/api/car/root.js
- Update ReadMe.md
- Add /src/routes/ReadMe.md
- Fix /api/car route
- Update Postmann Collection
> Information updates and minor fix

- README.md
- RestAPI.postman_collection.json
- src/routes/ReadMe.md
- Update /src/routes/ReadMe.md /api/users/login
- Update Postmann Collection
> - Update ReadMe.md server name

- src/authorisation/accessTokenModel.js
- src/authorisation/routeMethods.js
- src/database/accessTokensDBHelper.js
- src/database/dbHelper.js
- src/routes/api/users.js
Guckt mal bitte drüber, ob die Query passt.
> fix saveAccessToken update query

- package-lock.json
- package.json
- src/authorisation/routeMethods.js
isAuthorise gibt prüft den User mit dem Token ab, behandelt die Fehler und gibt user id, blocked status, authorityLevel und expiration date zurück.
cors package hinzugefügt
> isAuthorize / cors package

- src/authorisation/routeMethods.js
- src/car/routeMethods.js
- src/routes/api/users.js
- src/routes/root.js
Gibt ein JSON-Objekt zurück:
- loginStatus: "success" oder "failure"
- authorizationLevel: 1-4
Falls ein User geblockt ist, gibt loginStatus auch "failure" zurück.
> Login authorization

- src/car/routeMethods.js
- src/database/dbHelper.js
- src/routes/api/car.js
- Route für annulment transactions hinzugefügt
- Lesen der Transaktionen aus der Datenbank und Übergabe als JSON-Objekt
> Route for annulment transactions

- package-lock.json
- package.json
- src/accounts/carAccount.js
- src/accounts/userAccount.js
- src/blockchain/transaction.js
- test/accounts/carAccount.test.js
- test/accounts/userAccount.test.js
- test/blockchain/transaction.test.js
so far a few tests for class instanciation
> first tests

- src/authorisation/routeMethods.js
- src/car/routeMethods.js
- src/database/dbHelper.js
- Blocked = false beim User anlegen, da es weder übergeben noch ausgelesen wird und es nicht null sein darf
- UserID wird bei annulment_transaktions mit übergeben
> annulment_transaktion, blocked

- package-lock.json
- src/car/routeMethods.js
- src/database/dbHelper.js
Gibt user_id, vin, rejected, transactionHash zurück
> Annulment Transaktion

- VINI Rest API.postman_collection.json
- src/authorisation/routeMethods.js
- src/car/routeMethods.js
W0L000051T2123456 liefert nun auch die dummy Autos zurück.
Nicht vergessen die Dummy-Sachen am Ende zu entfernen.
@BreakBB @benders-mueller @lstuckstette @janzse @nils91 @Mattn81 
Wenn ihr Traksaktionen / Autos zur Blockchain hinzufügt bitte gültige VINS verwenden:
Könnt ihr hier prüfen:
https://sgse18.github.io/VINI/
einfach VIN eingeben und auf SUCHE klicken. Wenn das Feld nicht rot wird, ist sie gültig
> fix various errors (routes), update the postman script

- src/authorisation/routeMethods.js
- src/database/dbHelper.js
> fixed /api/users getAllUsers route - added blocked flag in response

- src/car/routeMethods.js
- src/database/msSqlWrapper.js
> kleiner fix

- src/car/routeMethods.js
- src/database/dbHelper.js
- src/database/msSqlWrapper.js
- msSqlWrapper: ungebrauchte Funktion **executeSqlJSON** entfernt
- einige Funktion für den dbHelper hinzugefügt
- getAllAnnulmentTransactions
> getAllAnnulmentTransactions

- src/app.js
- src/authorisation/accessTokenModel.js
- src/blockchain/ethNode.js
- src/database/tokenDBHelper.js
- src/utils.js
* Add interval to check the node connection every 2 minutes
* Add interval to delete expired tokens every 5 minutes.
* Update getTimestamp to use GTM+00:00 date.
> Update date checks and token expiration

- src/authorisation/routeMethods.js
- src/car/routeMethods.js
- src/database/dbHelper.js
- src/routes/ethTest.js
* Refactor GET /cancelTransaction "getAllAnnulmentTransactions" to require just one DB query
* Refactor DB functions getAllAnnulments, getAnnulment, insertAnnulment and acceptAnnulment
* Fix registerUser to use req.body.password again but send an email as well
* Update annulment_transactions DB table with FK vin and applicant column
> Major refactorings

- VINI Rest API.postman_collection.json
- src/database/dbHelper.js
> Remove obsolete addAnnulmentTransaction function from dbHelper.

- src/authorisation/routeMethods.js
- src/car/routeMethods.js
der Transaction-Hash wird nun auf ungleich der Länge (64) geprüft. Oder darf er wirklich größer sein?
> fix transactionHash check for insertAnnulmentTransaction

- src/blockchain/README.md
added a README.md for the blockchain folder which describes how to switch to another Blockchain (BC).
> added a README.md for the blockchain folder.
